name: CI Pipeline_2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: give permission to script
        run: sudo chmod +x ./script.sh

      - name: run script
        run: ./script.sh

      - name: list files
        run: ls -la
