name: CI Pipeline_2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: give permission to script
        run: chmod +x ./script.sh

      - name: run script
        run: ./script.sh


