name: CI Pipeline_2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: docker setup
        uses: docker/setup-buildx-action@v2

      - name: echo docker details
        run: echo info

      - name: run image
        run: docker run hello-world


